ppo-directive:
  trainable:
    type: str
    choice: PPO
  rollouts:
    num-workers:
      type: int
      choice: 4
    num-envs-per-worker:
      type: int
      choice: 2
    rollout_fragment_length:
      type: int
      choice: 64
  framework:
    type: str
    choice: torch
  training:
    lr:
      type: float
      choice: 0.0003
    lambda_:
      type: float
      choice: 0.95
    gamma:
      type: float
      choice: 0.99
    sgd_minibatch_size:
      type: int
      choice: 128
    train_batch_size:
      type: int
      choice: 512
    num_sgd_iter:
      type: int
      choice: 20
    use_gae:
      type: bool
      choice: true
    clip_param:
      type: float
      choice: 0.2
    model:
      type: dict
      choice: {
        "fcnet_hiddens": [256, 256],
        "use_lstm": false,
        }
  resources:
    num_gpus:
      type: int
      choice: 0
  evaluation:
    evaluation-interval:
      type: int
      choice: 4000
    evaluation-duration:
      type: int
      choice: 100

env-directive:
  prefix:
    type: str
    choice: simple-corridor-v0
  custom_env_class_name:
    type: str
    choice: SimpleCorridor
  custom_env_class_creator:
    type: str
    choice: simple_corridor_creator
  env_config:
    type: dict
    choice: {
      "corridor_length": 5,
      }
